"""
p2_sum_even_fibonacci_nums.py:
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. Bij starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find thesum of the even-valued terms.
"""


def sum_even_fib(limit):
    f0 = 0
    f1 = 1
    fn = f0 + 1 + f1
    sum_even = 0

    while fn < limit:
        sum_even += fn
        f0 = f1 + fn
        f1 = fn + f0
        fn = f0 + f1

    return sum_even


if __name__ == '__main__':
    print(sum_even_fib(4000000))
